[package]
name = "yang"
version = "0.1.0"
authors = ["武安祥 <wuanxiang@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "yang"
path = "src/lib.rs"


[dependencies]
clap = "2.33.0"
