[package]
name = "yang"
version = "0.1.0"
authors = ["武安祥 <wuanxiang@outlook.com>"]
edition = "2018"

[lib]
name = "yang"
path = "src/lib.rs"


[dependencies]
clap = "2.33.3"
nom  = "5.1.2"
getset = "0.1.1"
