[package]
name = "yang"
version = "0.1.0"
authors = ["武安祥 <wuanxiang@outlook.com>"]
edition = "2018"

[lib]
name = "yang"
path = "src/lib.rs"


[dependencies]
clap = "3.0.12"
nom  = "7.1.0"
getset = "0.1.2"
